src/Entity/Cars.php
<?php

namespace App\Entity;

use App\Repository\CarsRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints\Date;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: CarsRepository::class)]
#[Vich\Uploadable]
class Cars
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $price = null;
    
    #[ORM\Column(length: 255)]
    private ?string $brand = null;

    #[ORM\Column]
    private ?int $release_year = null;

    #[ORM\Column]
    private ?int $mileage = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $technical = null;

    #[ORM\Column(length: 255)]
    private ?string $feature = null;

    #[ORM\Column(length: 255)]
    private ?string $equipement = null;

    #[ORM\Column(length: 255)]
    private ?string $more_option = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[Vich\UploadableField(mapping: 'cars', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\OneToMany(mappedBy: 'cars', targetEntity: CarsImages::class, cascade: ['persist'])]
    private Collection $carsImages;

    public function __construct()
    {
        $this->carsImages = new ArrayCollection();
    }

    // #[ORM\Column(nullable: true)]
    // private ?\DateTimeImmutable $updatedAt = null;  
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->release_year;
    }

    public function setReleaseYear(int $release_year): static
    {
        $this->release_year = $release_year;

        return $this;
    }

    public function getMileage(): ?int
    {
        return $this->mileage;
    }

    public function setMileage(int $mileage): static
    {
        $this->mileage = $mileage;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTechnical(): ?string
    {
        return $this->technical;
    }

    public function setTechnical(string $technical): static
    {
        $this->technical = $technical;

        return $this;
    }

    public function getFeature(): ?string
    {
        return $this->feature;
    }

    public function setFeature(string $feature): static
    {
        $this->feature = $feature;

        return $this;
    }

    public function getEquipement(): ?string
    {
        return $this->equipement;
    }

    public function setEquipement(string $equipement): static
    {
        $this->equipement = $equipement;

        return $this;
    }

    public function getMoreOption(): ?string
    {
        return $this->more_option;
    }

    public function setMoreOption(string $more_option): static
    {
        $this->more_option = $more_option;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    /**
     * @return Collection<int, CarsImages>
     */
    public function getCarsImages(): Collection
    {
        return $this->carsImages;
    }

    public function addCarsImage(CarsImages $carsImage): static
    {
        if (!$this->carsImages->contains($carsImage)) {
            $this->carsImages->add($carsImage);
            $carsImage->setCars($this);
        }

        return $this;
    }

    public function removeCarsImage(CarsImages $carsImage): static
    {
        if ($this->carsImages->removeElement($carsImage)) {
            // set the owning side to null (unless already changed)
            if ($carsImage->getCars() === $this) {
                $carsImage->setCars(null);
            }
        }

        return $this;
    }

}

src/Controller/CarsController.php
<?php

namespace App\Controller;

use App\Entity\Cars;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\CarsRepository;
use App\Repository\HoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use function PHPSTORM_META\type;

class CarsController extends AbstractController
{
    #[Route('/ventes', name: 'app_cars')]
    public function index(
        CarsRepository $carsRepository, 
        HoursRepository $hoursRepository, 
        Request $request,
        PaginatorInterface $paginator): Response
    {
        $minMaxValues = [
            'minMileage' => $carsRepository->findMinMaxMileage()['minMileage'],
            'maxMileage' => $carsRepository->findMinMaxMileage()['maxMileage'],
            'minReleaseYear' => $carsRepository->findMinMaxReleaseYear()['minReleaseYear'],
            'maxReleaseYear' => $carsRepository->findMinMaxReleaseYear()['maxReleaseYear'],
            'minPrice' => $carsRepository->findMinMaxPrice()['minPrice'],
            'maxPrice' => $carsRepository->findMinMaxPrice()['maxPrice'],
        ];

        $hours = $hoursRepository->findAll();
        
        $cars = $paginator->paginate(
            $carsRepository->findBy([], ['id' => 'DESC']),
            $request->query->getInt('page', 1),
            3
        );
                
        return $this->render('pages/cars/cars.html.twig',[ 
            'cars' => $cars,
            'hours' => $hours,
            'minMaxValues' => $minMaxValues,
        ]);    
    }  

    #[Route('/filter', name: 'app_filterCars')]
    public function filter (
        Request $request,
        CarsRepository $carsRepository): JsonResponse
        {
            $minMaxValues = [
                'minMileage' => $carsRepository->findMinMaxMileage()['minMileage'],
                'maxMileage' => $carsRepository->findMinMaxMileage()['maxMileage'],
                'minReleaseYear' => $carsRepository->findMinMaxReleaseYear()['minReleaseYear'],
                'maxReleaseYear' => $carsRepository->findMinMaxReleaseYear()['maxReleaseYear'],
                'minPrice' => $carsRepository->findMinMaxPrice()['minPrice'],
                'maxPrice' => $carsRepository->findMinMaxPrice()['maxPrice'],
            ];
    
            $minMileage = $request->query->get('minMileage');
            $maxMileage = $request->query->get('maxMileage');
            $minReleaseYear = $request->query->get('minReleaseYear');
            $maxReleaseYear = $request->query->get('maxReleaseYear');
            $minPrice = $request->query->get('minPrice');
            $maxPrice = $request->query->get('maxPrice');
    
            $filteredCars = $carsRepository->FindFilteredCars($minMileage, $maxMileage, $minReleaseYear, $maxReleaseYear, $minPrice, $maxPrice);

            return new JsonResponse([
                'content' => $this->renderView('pages/cars/_filterCars.html.twig', 
                ['cars' => $filteredCars,
                'minMaxValues' => $minMaxValues,
            ]),
            ]);
    }
    
    #[Route('/cars/{id}', name: 'app_cars_show')]
    public function show(
        HoursRepository $hoursRepository, 
        Cars $car): Response 
        {
            $hours = $hoursRepository->findAll();
            
            $carImages = $car->getCarsImages();
            
            return $this->render('pages/cars/show.html.twig', [
                'car' => $car,
                'hours' => $hours,
                'carImages' => $carImages,
            ]);
        }
        
    }

templates/pages/cars/_filterCars.html.twig
{% for car in cars %}
<div class="col-md-4 my-2 d-flex">
    <div class="card w-100">
      {% if car.imageName %}
        <img src="{{ vich_uploader_asset(car, 'imageFile') }}" class="card-img-top" alt="photo de {{ car.brand }}">
        {% else %}
        <img src="{{ asset('build/images/default_image.png') }}" class="card-img-top" alt="photo de {{ car.brand }}">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{ car.brand }}</h5>
        <p class="card-text">{{ car.model }}</p>
        <p class="card-text">{{ car.releaseYear }}</p>
        <p class="card-text">{{ car.price }} €</p>
        <p class="card-text">{{ car.mileage }} km</p>
        <a href="{{ path('app_cars_show', {'id': car.id}) }}" class="btn btn-primary btn-contact">Plus de détails</a>
      </div>
    </div>
</div>
{% endfor %}

templates/pages/cars/cars.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Garage V. Parrot - Voitures
{% endblock %}

{% block body %}
  <div class="container mt-4 js-filter">
    <div class="row d-flex justify-content-between mb-4">
      <div class="form-group col-md-3 js-filter-form">
        <label for="filterMileage" class="form-label">Kilométrage :</label>
        <div id="mileage-slider" data-min="{{ minMaxValues.minMileage }}" data-max="{{ minMaxValues.maxMileage }}">
        </div>
        <div class="row align-items-center mt-4">
          <label for="minMileage" class="col-form-label col-2">Min:</label>
          <div class="col-4">
            <input type="text" id="minMileage" value="{{ minMaxValues.minMileage }}" readonly class="form-control">
          </div>
          <label for="maxMileage" class="col-form-label col-2">Max:</label>
          <div class="col-4">
            <input type="text" id="maxMileage" value="{{ minMaxValues.maxMileage }}" readonly class="form-control">
          </div>
        </div>
      </div>
      <div class="form-group col-md-3 js-filter-form">
        <label for="filterYear" class="form-label">Année :</label>
        <div id="releaseYear-slider" data-min="{{ minMaxValues.minReleaseYear }}" data-max="{{ minMaxValues.maxReleaseYear }}">
        </div>
        <div class="row align-items-center mt-4">
          <label for="minReleaseYear" class="col-form-label col-2">Min:</label>
          <div class="col-4">
            <input type="text" id="minReleaseYear" value="{{ minMaxValues.minReleaseYear }}" readonly class="form-control">
          </div>
          <label for="maxReleaseYear" class="col-form-label col-2">Max:</label>
          <div class="col-4">
            <input type="text" id="maxReleaseYear" value="{{ minMaxValues.maxReleaseYear }}" readonly class="form-control">
          </div>
        </div>
      </div>
      <div class="form-group col-md-3 js-filter-form">
        <label for="filterPrice" class="form-label">Prix :</label>
        <div id="price-slider" data-min="{{ minMaxValues.minPrice }}" data-max="{{ minMaxValues.maxPrice }}">
        </div>
        <div class="row align-items-center mt-4">
          <label for="minPrice" class="col-form-label col-2">Min:</label>
          <div class="col-4">
            <input type="text" id="minPrice" value="{{ minMaxValues.minPrice }}" readonly class="form-control">
          </div>
          <label for="maxPrice" class="col-form-label col-2">Max:</label>
          <div class="col-4">
            <input type="text" id="maxPrice" value="{{ minMaxValues.maxPrice }}" readonly class="form-control">
          </div>
        </div>
      </div>
    </div>

  <div data-action-url="{{ path('app_filterCars' )}}">
  </div>

  {% if not cars.items is same as ([]) %}
    <div class="count">
        <h3>Il y a {{ cars.getTotalItemCount }} voitures disponibles à la vente.</h3>
    </div>

    {% if form is defined and form is not null %}
      {{ form(form) }}
    {% endif %}

    <div class="showCar row text-center js-filter-content" id="filterForm">
      {% for car in cars %}
        {% include "partials/_cars.html.twig" with {'car' : car} %}
      {% endfor %}
    </div>
    
    <div class="navigation d-flex justify-content-center mt-4 js-filter-pagination">
      {{ knp_pagination_render(cars) }}
    </div>
      {% else %}
    <div>
      <h3>Il n'y a pas de voiture de disponible à la vente.</h3>
    </div>
  {% endif %}
  </div>
{% endblock %}

templates/pages/cars/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="row align-items-start g-5 py-5">
    <div class="col-lg-5">
      <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">{{ car.brand }}</h1>
      <p class="lead">{{ car.description }}</p>
      <div class="d-grid gap-2 gap-md-3 mt-4 showCar">
        <p class="showCarDetails">Modèle</p>
        <p class="card-text text-center">{{ car.model }}</p>
        <p class="showCarDetails">Année de mise en circulation</p>
        <p class="card-text text-center">{{ car.releaseYear }}</p>
        <p class="showCarDetails">Prix</p>
        <p class="card-text text-center">{{ car.price }} €</p>
        <p class="showCarDetails">Carburant</p>
        <p class="card-text text-center">{{ car.technical }}</p>
        <p class="showCarDetails">Kilométrage</p>
        <p class="card-text text-center">{{ car.mileage }} km</p>
        <p class="showCarDetails">Type de boite</p>
        <p class="card-text text-center">{{ car.feature }}</p>
        <p class="showCarDetails">Equipement(s)</p>
        <p class="card-text text-center">{{ car.equipement }}</p>
        <p class="showCarDetails">Option(s)</p>
        <p class="card-text text-center">{{ car.moreOption }}</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mt-4">
          <a href="{{ path('app_contact', {'subject' : 'Demande d\'information pour la ' ~ car.brand ~ ' ' ~ car.model }) }}" class="btn btn-primary btn-contact btn-lg px-4 gap-3">Contacter pour ce véhicule</a>
        </div>
      </div>
    </div>
    <div class="col-lg-7">
    {% if car.imageName %}
      <img src="{{ vich_uploader_asset(car, 'imageFile') }}" class="card-img-top" alt="photo de {{ car.brand }}">
      <div class="row mt-3">
      {% for image in carImages %}
        <div class="col-4">
          <img src="{{ vich_uploader_asset(image, 'imageFile') }}" class="card-img-top" alt="photos supplémentaires de la voiture">
        </div>
      {% endfor %}
      </div>
      {% else %}
        <img src="{{ asset('build/images/default_image.png') }}" class="card-img-top" alt="photo de {{ car.brand }}">
    {% endif %}
    <div class="breadcrumbs">
      <div class="d-flex justify-content-end">
        <a href="javascript:history.back(1)">Revenir à la page précédente</a>
      </div>
    </div>
  </div>

  </div>
{% endblock %}